// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace lucky_api.Models
{
    public partial class Config
    {
        [Key]
        public int ID { get; set; }
        [StringLength(255)]
        public string Background { get; set; }
        public int? WatingTime { get; set; }
    }
}