// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace lucky_api.Models
{
    public partial class Emp
    {
        [Key]
        public int EmpID { get; set; }
        [StringLength(10)]
        public string EmpCode { get; set; }
        [StringLength(255)]
        public string EmpName { get; set; }
        [StringLength(50)]
        public string EmpDept { get; set; }
        public bool Visible { get; set; }
    }
}