// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;

namespace lucky_api.Models
{
    public partial class Prize
    {
        [Key]
        public int? PrizeID { get; set; }
        [StringLength(255)]
        public string PrizeName { get; set; }
        public int? Qty { get; set; }
        public int? SpinTime { get; set; }
        public string Image { get; set; }
        public bool? Visible { get; set; }
        public int Seq { get; set; }
    }
}